[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
token_pool = "3JMqhHBkh9vFciBjzMAy9x3ksyKnSC2UbTbQr4atkVBo"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "http://localhost:8899"
# cluster = "https://api.devnet.solana.com"
# cluster = "https://solana-devnet.g.alchemy.com/v2/xOw_vw5ZnqjQsPr9ILoZcA98LV5rrGVJ"
# cluster = "https://devnet.helius-rpc.com/?api-key=0300593e-fad8-43ce-8244-fdeafa72bbcd"
# cluster = "https://api.testnet.solana.com"
cluster = "https://api.testnet.v1.sonic.game"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/logic/index.ts"
test_step1 = "cross-env step=1 yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/logic/index.ts"
test_step2 = "cross-env step=2 yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/logic/index.ts"
test_step3 = "cross-env step=3 yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/logic/index.ts"
build = "anchor build"
reTest = "anchor deploy && anchor run test"
